export { DashboardPage } from './Dashboard'
export { RestaurantPage } from './Restaurant'
export { CategoriesPage } from './Categories'
export { SubcategoriesPage } from './Subcategories'
export { ProductsPage } from './Products'
export { AllergensPage } from './Allergens'
export { SettingsPage } from './Settings'
